version: '3.7'
services:
  dyna-rest-app:
    build:
      context: .
    depends_on:
      - mysql
      - mongo
    ports:
      - 8080:8080
  mysql:
    restart: always
    image: mysql
    environment:
      MYSQL_DATABASE: resources
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  mongo:
    image: mongo
    restart: always
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
  adminer:
    image: adminer
    restart: always
    depends_on:
      - mysql
    ports:
      - 9000:8080
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 9001:8081
    environment:
      #ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo
volumes:
  mysql_data:
  mongodb_data: